### ISSUE TITLE
Travis CI build failed

### ISSUE THREAD

**Issue by linuxenko** [linuxenko/umediashare#4]
## Travis CI build problem

Looks like broccoli-funnel not were installed.

```
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building
Cannot find module 'broccoli-funnel'
Error: Cannot find module 'broccoli-funnel'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/linuxenko/umediashare/ember-cli-build.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/travis/build/linuxenko/umediashare/node_modules/ember-cli/lib/utilities/find-build-file.js:19:19)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/travis/build/linuxenko/umediashare/node_modules/ember-cli/lib/models/builder.js:50:21)
    at Class.module.exports.Task.extend.init (/home/travis/build/linuxenko/umediashare/node_modules/ember-cli/lib/models/builder.js:91:10)
    at new Class (/home/travis/build/linuxenko/umediashare/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/travis/build/linuxenko/umediashare/node_modules/ember-cli/lib/tasks/build.js:15:19)
```

**Comment by linuxenko** [comment]
next broccoli-merge-trees (

```
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building
Cannot find module 'broccoli-merge-trees'
Error: Cannot find module 'broccoli-merge-trees'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
```
